[build-system]
requires = ["scikit-build-core>=0.10"]
build-backend = "scikit_build_core.build"

[project]
name = "comparehypotheses"
version = "0.0.1"
description = "Compare kinematic fit performance for identical events present in analysis trees reconstructed under different kinematic fit hypotheses."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[tool.scikit-build]
wheel.packages = ["comp_hyp"]

[tool.scikit-build.cmake.define]
CMAKE_INSTALL_BINDIR = "comp_hyp/bin" 
CMAKE_EXE_LINKER_FLAGS = "-Wl,-rpath-link,/home/user/Documents/test/compareHypotheses/.venv/lib/python3.13/site-packages/root.libs"

[project.scripts]
compare_hypotheses = "comp_hyp:_comp_hyp_wrapper"

